"use client";
import Select from "react-select";
import { useState, useEffect } from "react";

export default function Report1() {
  const [models, setModels] = useState([]);
  const [selectedModel, setSelectedModel] = useState(null);
  const [report, setReport] = useState([]);

  useEffect(() => {
    const getModels = async () => {
      const response = await fetch(
        `http://localhost:3000/search/api?field=model_id&table=aircraft_model`
      );
      const models = await response.json();
      const formattedModels = models.rows.map((model) => ({
        value: model.model_id,
        label: model.model_id,
      }));
      setModels(formattedModels);
    };
    getModels();
  }, []);

  const handleModelChange = (selectedOption) => {
    setSelectedModel(selectedOption);
  };

  const handleGetReport = async (e) => {
    e.preventDefault();
    const response = await fetch(
      `http://localhost:3000/api/reports/5?model=${selectedModel.value}`
    );
    const report = await response.json();
    setReport(report);
  };

  return (
    <div className="font-nunito">
      <h1 className="text-xl mb-5">
        Total revenue generated by each Aircraft type
      </h1>
      <div className="flex flex-col gap-5 items-center">
        <form onSubmit={handleGetReport}>
          <div className="flex flex-row gap-3 items-center">
                <label>Model</label>
            <Select
              options={models}
              required
              value={selectedModel}
              onChange={handleModelChange}
            />
            <button
              onClick={handleGetReport}
              className="bg-slate-600 text-white rounded-md px-6 py-2"
            >
              Get Report
            </button>
          </div>
        </form>
        <table className="table-fixed">
          <thead>
            <tr>
              <th className="px-4 py-2">Revenue</th>
            </tr>
          </thead>
          <tbody>
            {report.length === 0 ? (
              <tr>
                <td colSpan="2" className="text-center">
                  No results found
                </td>
              </tr>
            ) : (
              report.map((item) => (
                <tr key={item.class_name} className="text-center">
                <td className="border px-4 py-2">LKR.{item.revenue.toLocaleString('en-GB')}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
