'use client';
import Select from "react-select";
import {useState, useEffect} from 'react'; 

export default function Report1() {
        const [models, setModels] = useState([]); 
        const [selectedModel, setSelectedModel] = useState(null);

        useEffect(() => {   
                const getModels = async () => {
                        const response = await fetch(`http://localhost:3000/search/api?field=model_id&table=aircraft_model`);
                        const models = await response.json();
                        const formattedModels = models.rows.map(model => ({value: model.model_id, label: model.model_id}));
                        setModels(formattedModels);
                };
                getModels();
        }, []);

        const handleModelChange = (selectedOption) => {
                setSelectedModel(selectedOption);
        }

        const handleGetReport = () => {
                console.log(selectedModel);
                // write code to fetch report data based on selectedModel
        }

    return (
        <div className="font-nunito flex flex-col gap-2">
            <h1>Total revenue generated by each Aircraft type</h1>
            <div className="flex flex-row gap-3">
                <Select 
                options={models}
                required
                value={selectedModel}
                onChange={handleModelChange}
                />
                <button onClick={handleGetReport} className="bg-slate-600 text-white rounded-md px-6 py-2">Get Report</button>
            </div>
        </div>
    );
}